## Coding Exercise #0207

### 1. Correlation:

In [25]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [26]:
# Go to the directory where the data file is located. 
             # Please, replace the path with your own.  

In [27]:
# Read in the data.
df = pd.read_csv('iris.csv', header='infer')

In [28]:
df.shape

(150, 5)

In [29]:
df.head(3)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa

In [30]:
# Set aside two variables.
x = df['petal.length']
y = df['sepal.length']

#### 1.1. Pearson:

In [31]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)           

array([0.872, 0.   ])

In [32]:
# Using the Pandas function.
x.corr(y)

0.871753775886583

In [33]:
# Correlation array.
np.round(df.corr(),3)               

sepal.length  sepal.width  petal.length  petal.width
sepal.length         1.000       -0.118         0.872        0.818
sepal.width         -0.118        1.000        -0.428       -0.366
petal.length         0.872       -0.428         1.000        0.963
petal.width          0.818       -0.366         0.963        1.000

#### 1.2. Spearman:

In [34]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)          

array([0.882, 0.   ])

#### 1.3. Kendall:

In [35]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)         # Correlation coefficient and p-value.

array([0.719, 0.   ])

### 2. Interval Estimation of the Correlation:

In [36]:
# Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')

In [37]:
df.head(3)

Name Gender  Age  Grade Absence Bloodtype  Height  Weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [38]:
# Set aside two variables.
x = df.Height
y = df.Weight

#### 2.2. Confidence Interval of the Pearson Correlation: 

In [39]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [40]:
# 95% confidence interval. 
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [41]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}